spring:
    datasource:
        url: jdbc:postgresql://ep-lucky-queen-69256101.ap-southeast-1.aws.neon.tech/neondb?user=jarryscript&password=Q0l7YVmgzjaF
        driver-class-name: org.postgresql.Driver
        hikari:
            connection-timeout: 20000
            maximum-pool-size: 5
            minimum-idle: 1
            idle-timeout: 300000
            max-lifetime: 1800000
            pool-name: MyHikariPool
    jpa:
        hibernate:
            ddl-auto: update

